tap 'caskroom/cask'

brew 'git'
brew 'npm'
brew 'yarn'

cask '1password'
cask 'bartender'
cask 'blender'
cask 'carbon-copy-cloner'
cask 'cleanmymac'
cask 'discord'
cask 'dropbox'
cask 'etcher'
cask 'figma'
cask 'google-chrome'
cask 'imageoptim'
cask 'notion'
cask 'openemu'
cask 'plex-media-server'
cask 'skyfonts'
cask 'spotify'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'vlc'
