tap 'caskroom/cask'

brew 'git'
brew 'npm'

cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'atom'
cask 'bartender'
cask 'cleanmymac'
cask 'dropbox'
cask 'etcher'
cask 'firefox'
cask 'fluid'
cask 'franz'
cask 'google-chrome'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2'
# cask 'nudgit'
cask 'omnifocus'
cask 'opera'
cask 'paparazzi'
cask 'parallels-desktop'
cask 'sitesucker'
cask 'sketch'
# cask 'skyfonts'
cask 'spectacle'
cask 'spotify'
cask 'the-unarchiver'
cask 'tableau-public'
cask 'trasmit'
cask 'vlc'
cask 'visual-studio-code'

mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Simplenote', id: 692867256 