tap 'caskroom/cask'

brew 'git'
brew 'npm'

cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'bartender'
cask 'cleanmymac'
cask 'dropbox'
cask 'etcher'
cask 'firefox'
cask 'fluid'
cask 'franz'
cask 'google-chrome'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2'
# cask 'nudgit'
cask 'opera'
cask 'paparazzi'
cask 'parallels-desktop'
cask 'sketch'
cask 'skyfonts'
cask 'spectacle'
cask 'spotify'
cask 'tableau-public'
cask 'the-unarchiver'
cask 'transmit'
cask 'vlc'
cask 'visual-studio-code'
cask 'wavebox'